[general]
# Directories to search for templates, relative to the crate root.
dirs = [ "src/kotlin/templates", "src/python/templates", "src/swift/templates", "src/ruby/templates" ]

[[syntax]]
name = "c"

[[syntax]]
name = "kt"

[[syntax]]
name = "py"

[[syntax]]
name = "swift"

[[syntax]]
name = "rb"
